name: deptrac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deptrac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run tests via PHPStan
        run: composer deptrac
