name: Rector

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies via Composer
        run: composer install --no-interaction --prefer-dist

      - name: Run checks via Rector
        run: composer phpstan
